### PR TITLE
Adds chart.js

### PR DESCRIPTION
**Pull request by binarymason**
No styling applied. :smile:

Note: need to add language background colors.
Would like the colors to match up with what's on GitHub.
Will grab https://github.com/github/linguist/blob/master/lib/linguist/languages.yml
in another iteration.

Thinking this will be better accomplished in a node environment instead
of native html.  That will also open the door for the shell script that
will shallow clone repos and count lines of code for an author for each
language.

Screenshot:
image

### CODE REVIEW

**Review by savvmae — APPROVED** [review]
Looks great man! I was just starting to get into chart.js. You're doing all the hard stuff for us ;)

**Comment by CTAnthny** [comment]
lol, yeah, I'm having a hard time keeping up. Some of this stuff is still over my head until I learn more, so I'm not sure what I can help with, but don't let me slow you down!

**Comment by binarymason** [comment]
All good guys!  This is still super rough, so if you'd like to add some simple html or css that would definitely be welcome (and needed!).

**Comment by CTAnthny** [comment]
I cloned the repo and added some of the rgba color values into the script similar to how graph.js had in the doc, but I'm not sure how to integrate it into the functions/promises you have going. There are only a couple language colors but I can pull in more as well... how many languages do you think? All of them? What sort of html and css layout are you thinking of?

**Pull request merged**
